sudo: false
language:
   - cpp
compiler: g++
os: linux

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7

before_install:
	- mkdir build
    - cd build
    - cmake ..
script:
    - make test
    - ./tests




