sudo: false
language:
   - cpp
compiler: g++
os: linux

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7

before_install:
	- sudo apt-get install libgtest-dev
        - git clone https://github.com/google/googletest.git
        - cd googletest
        - mkdir mybuild
        - cd mybuild
        - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=ON -DINSTALL_GTEST=ON -DINSTALL_GMOCK=ON ../       
        - make                             # build the static and shared libraries libraries
        - cd ../../
script:
    - make test
    - ./test




